// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBPEcDSh4uA11tlvv45a7mmS-IveJJhXCQ',
    appId: '1:975494418934:web:e29c3c37aeb58f38b737d7',
    messagingSenderId: '975494418934',
    projectId: 'anubandhit-dd0f6',
    authDomain: 'anubandhit-dd0f6.firebaseapp.com',
    storageBucket: 'anubandhit-dd0f6.appspot.com',
    measurementId: 'G-GEN5V496H7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3dTMx-u8rGcZ08gnBRKci9rNu-WRMYpU',
    appId: '1:975494418934:android:6de103afb317c5a0b737d7',
    messagingSenderId: '975494418934',
    projectId: 'anubandhit-dd0f6',
    storageBucket: 'anubandhit-dd0f6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUegAHc9oJ6cELxK-HdcT14am96lts22A',
    appId: '1:975494418934:ios:1a1d15c38f53213cb737d7',
    messagingSenderId: '975494418934',
    projectId: 'anubandhit-dd0f6',
    storageBucket: 'anubandhit-dd0f6.appspot.com',
    androidClientId: '975494418934-u9udpof3lmdcu1um98uh978rc7krrvq3.apps.googleusercontent.com',
    iosClientId: '975494418934-cl45lrq3qv6u546k8jq6jfuvg636hliv.apps.googleusercontent.com',
    iosBundleId: 'com.example.anubandhit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBUegAHc9oJ6cELxK-HdcT14am96lts22A',
    appId: '1:975494418934:ios:1a1d15c38f53213cb737d7',
    messagingSenderId: '975494418934',
    projectId: 'anubandhit-dd0f6',
    storageBucket: 'anubandhit-dd0f6.appspot.com',
    androidClientId: '975494418934-u9udpof3lmdcu1um98uh978rc7krrvq3.apps.googleusercontent.com',
    iosClientId: '975494418934-cl45lrq3qv6u546k8jq6jfuvg636hliv.apps.googleusercontent.com',
    iosBundleId: 'com.example.anubandhit',
  );
}
